-- +goose Up
ALTER TABLE projects ADD COLUMN IF NOT EXISTS install_cmd TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS root_dir TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS node_version TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS port_override INT NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS memory_mb INT NOT NULL DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS cpus NUMERIC(3,2) NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE projects DROP COLUMN IF EXISTS install_cmd;
ALTER TABLE projects DROP COLUMN IF EXISTS root_dir;
ALTER TABLE projects DROP COLUMN IF EXISTS node_version;
ALTER TABLE projects DROP COLUMN IF EXISTS port_override;
ALTER TABLE projects DROP COLUMN IF EXISTS memory_mb;
ALTER TABLE projects DROP COLUMN IF EXISTS cpus;
